[project]
name = "logger"
version = "0.1.0"
description = ""
requires-python = ">=3.10"

dependencies = []

[build-system]
requires = ["hatchling>=1.13.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/logger"]